version: 2
updates:
  # Maintain dependencies the LoRa Engine
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "daily"
    # Maintain dependencies for the web client
  - package-ecosystem: "npm"
    directory: "/src/AzureIoTHub.Portal/Client"
    schedule:
      interval: "daily"