version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies the LoRa Engine
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Maintain dependencies for the web client
  - package-ecosystem: "npm"
    directory: "/src/IoTHub.Portal/Client"
    schedule:
      interval: "daily"