image: python:latest

tasks:
  - name: mkdocs-material
    init: pip install -r requirements.txt
    command: |
      export PATH="$PATH:/home/gitpod/.local/bin"
      mkdocs serve

ports: 
  - port: 8000
    onOpen: open-preview
