coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit
ignore: 
   - "**/Startup.cs"
   - "**/Startup/*.cs"
   - "**/Program.cs"
   - "**/PortalDbContext.cs"
   - "**/Migrations/*.cs"
   - "**/Seeds/*.cs"
   - "**/PortalDbContextFactory.cs"   