# Project information
site_name: IoT Hub Portal
site_description: IoT Hub Portal for device management

# Repository
repo_name: CGI-FR/IoT-Hub-Portal
repo_url: https://github.com/CGI-FR/IoT-Hub-Portal
edit_uri: edit/docs/main/docs/

# Copyright
copyright: Copyright &copy; 2022 CGI France

# Configuration
theme:
  name: material
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.svg
  logo: assets/images/logo.svg

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins
plugins:
  - search:
      lang: en
  - macros
  - swagger-ui-tag:
      supportedSubmitMethods: []
      filter: true

# Extra
extra:
  version:
    provider: mike

# Navigation
nav:
  - index.md
  - Azure: 'azure.md'
  - AWS: 'aws.md'
  - Dev Guide:
    - 'Developer Guide': 'dev-guide.md'
    - 'Testing':
      - 'dev-guide/testing/unit-tests-common-practices.md'
      - 'dev-guide/testing/unit-tests-on-blazor-components.md'
    - 'Migrations':
      - 'dev-guide/migrations/v3-to-v4.md'
      - 'dev-guide/migrations/v4-to-v5.md'
      - 'dev-guide/migrations/v5-to-v6.md'
    - 'Project conception':
      - 'dev-guide/conception/diagrams.md'
  - Concepts: 'concepts.md'
  - Web API Reference: 'open-api.md'
  - About:
    - 'Known Issues': 'about/issues.md'
    - 'Support': 'about/support.md'
    - 'Credits': 'about/credits.md'
    - 'License': 'about/license.md'