// <auto-generated />
using IoTHub.Portal.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IoTHub.Portal.MySql.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20220910143007_Add Quartz .NET tables")]
    partial class AddQuartzNETtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            
#pragma warning restore 612, 618
        }
    }
}
