// <auto-generated />

#nullable disable

namespace IoTHub.Portal.MySql.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20220910143007_Add Quartz .NET tables")]
    partial class AddQuartzNETtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            
#pragma warning restore 612, 618
        }
    }
}
