AWSTemplateFormatVersion: 2010-09-09
Description: AWS S3 storage template | PostgreSQL database storage template | Application Runner template

Parameters:
  UniqueSolutionPrefix:
    Type: String
    Description: Prefix used for resource names. Should be unique as this will also be used for bucket and database name. Should not contain uppercase letters
    MinLength: '1'
    MaxLength: '20'
    ConstraintDescription: Should be less than 20 letters
    AllowedPattern: '^[a-z]+$'
  pgsqlAdminLogin:
      Type: String
      Description: PostgreSQL user
      MinLength: '1'
      MaxLength: '30'
  pgsqlAdminPassword:
      Type: String
      NoEcho: 'true'
      Description: PostgreSQL password
      MinLength: '8'
      MaxLength: '41'
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnet1:
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Type: AWS::EC2::Subnet::Id
  Subnet3:
    Type: AWS::EC2::Subnet::Id
  awsAccess:
    Type: String
    Description: Access Sectet
  awsAccessSecretkey:
    Type: String
    Description: Bucket Name
    Default: <Secret>
  regionCode:
    Type: String
    Description: Region code
    Default: eu-west-1
  openIdApiClientId:
    Type: String 
    Description: The Open ID API client ID for the B2C tenant
    Default: iot-portal-api
  openIdClientId:
    Type: String 
    Description: The Open ID client ID for the B2C tenant
    Default: iot-portal
  openIdAuthority:
    Type: String 
    Description: The Open ID Authority
    Default: https://cgigeiotdemoauth.azurewebsites.net/auth/realms/iot-portal
  openIdMetadataURL:
    Type: String 
    Description: The Open ID metadata Url from the Identity provider
    Default: https://cgigeiotdemoauth.azurewebsites.net/auth/realms/iot-portal/.well-known/openid-configuration
  openIdScopeName:
    Type: String 
    Description: The Open ID Scope name
    Default: iot_access

Resources:
#======== S3 Storage ==========
  s3Bucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: !Join [ "-", [!Ref UniqueSolutionPrefix, "bucket"] ] 

#======== PostgreSQL database ==========
  PostgreSQLDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain # CloudFormation keeps the resource without deleting the resource or its contents when the resource is replaced 
    UpdateReplacePolicy: Retain # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html
    Properties:
      DBInstanceIdentifier: !Join [ "-", [!Ref UniqueSolutionPrefix, "pgdbinstance"] ] 
      AllocatedStorage: '20' 
      DBInstanceClass: 'db.t2.micro' # A voir quel instance utilisé : https://instances.vantage.sh/rds/
      Engine: postgres
      EngineVersion: 12
      LicenseModel: postgresql-license
      MasterUsername: !Ref pgsqlAdminLogin
      MasterUserPassword: !Ref pgsqlAdminPassword
      DBName: !Join [ "_", [!Ref UniqueSolutionPrefix, "cgigeiotdemo"] ] 
      VPCSecurityGroups:
        - !Ref PgSQLSecurityGroup
      DBSubnetGroupName: !Ref PgSQLSubnetGroup
  PgSQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to the database instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
  PgSQLSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: pgSqlsubnetgroup
      DBSubnetGroupDescription: Subnets available for the database
      SubnetIds: # A voir le nombre de subnets qu'on veut dans le groupe
        - !Ref Subnet1
        - !Ref Subnet2
        - !Ref Subnet3

#============= App Runner - To Lunch the App ==============
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Join [ "-", [!Ref UniqueSolutionPrefix, "appRunner"] ]
      InstanceConfiguration:
        Memory: 2 GB
        InstanceRoleArn: arn:aws:iam::578920151383:role/aws-service-role/apprunner.amazonaws.com/AWSServiceRoleForAppRunner
      HealthCheckConfiguration:
        Protocol: "HTTP"
        Path: "/"
        Interval: 20
        Timeout: 5
        HealthyThreshold: 2
        UnhealthyThreshold: 5
      SourceConfiguration:
        AutoDeploymentsEnabled: false
        ImageRepository: 
          ImageConfiguration: 
            Port: 80 # This is The port that your application listens to in the container. It can be changed (To see)
            RuntimeEnvironmentSecrets: 
              #- Name: AWS__S3Storage__ConnectionString
                # Value: !Sub https://s3.${regionCode}.amazonaws.com/${bucketName}
              - Name: AWS__Access
                Value: !Sub ${awsAccess}
              - Name: AWS__AccessSecret
                Value: !Sub ${awsAccessSecretkey}
              - Name: AWS__Region
                Value: !Sub ${regionCode}
              #- Name: PostgreSQL__ConnectionString
                # Value: !Join [ "/", [ !Join ["@", [!Sub postgres://${pgsqlAdminLogin}:${pgsqlAdminPassword}, !Sub ${pgsqlHostName}:5432]], !Join [ "_", [!Ref UniqueSolutionPrefix, "cgigeiotdemo"] ]] ]
            RuntimeEnvironmentVariables: 
              - Name: OIDC__ApiClientId
                Value: !Sub '${openIdApiClientId}'
              - Name: OIDC__ClientId
                Value: !Sub '${openIdClientId}'
              - Name: OIDC__Authority
                Value: !Sub '${openIdAuthority}'
              - Name: OIDC__MetadataUrl
                Value: !Sub '${openIdMetadataURL}'
              - Name: OIDC__Scope
                Value: !Sub '${openIdScopeName}'
              - Name: CloudProvider
                Value: AWS
          ImageIdentifier: 'public.ecr.aws/d7e3t8n4/iothub-portal:latest' # Since we are using ECR_PUBLIC, we need to create mannually the ECR and put the ImageIdentifier here
          ImageRepositoryType: ECR_PUBLIC

