AWSTemplateFormatVersion: 2010-09-09
Description: PostgreSQL database storage template

Parameters:
  dBInstanceID:
    Default: pgdbinstance
    Description: PostgreSQL database instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  dBName:
      Type: String
      Default: cgigeiotdemo
      Description: Database name
      MinLength: '1'
      MaxLength: '64'
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  pgsqlAdminLogin:
      Type: String
      Description: PostgreSQL user
      MinLength: '1'
      MaxLength: '30'
  pgsqlAdminPassword:
      Type: String
      NoEcho: 'true'
      Description: PostgreSQL password
      MinLength: '8'
      MaxLength: '41'
  databaseInstanceClass:
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.m1.small
      - db.m1.medium
      - db.m1.large
    Type: String
    ConstraintDescription: Must select a valid database instance
    Default: db.t2.micro
    Description: The dataabse instance type
  allocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnet1:
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Type: AWS::EC2::Subnet::Id
  Subnet3:
    Type: AWS::EC2::Subnet::Id
  AllowedCIDR:
    Type: String
    Description: CIDR block that is allowed to access the database
    Default: 0.0.0.0/0
    AllowedPattern: '^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\/([0-9]|[1-2][0-9]|3[0-2]))?$'


Resources:
  PostgreSQLDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain # CloudFormation keeps the resource without deleting the resource or its contents when the resource is replaced 
    UpdateReplacePolicy: Retain # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html
    Properties:
      DBInstanceIdentifier: !Ref dBInstanceID
      AllocatedStorage: !Ref allocatedStorage 
      DBInstanceClass: !Ref databaseInstanceClass # A voir quel instance utilisé : https://instances.vantage.sh/rds/
      Engine: postgres
      MasterUsername: !Ref pgsqlAdminLogin
      MasterUserPassword: !Ref pgsqlAdminPassword
      DBName: !Ref dBName
      VPCSecurityGroups:
        - !Ref PgSQLSecurityGroup
      DBSubnetGroupName: !Ref PgSQLSubnetGroup

  PgSQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to the database instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref AllowedCIDR

  PgSQLSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: pgSqlsubnetgroup
      DBSubnetGroupDescription: Subnets available for the database
      SubnetIds: # A voir le nombre de subnets qu'on veut dans le groupe
        - !Ref Subnet1
        - !Ref Subnet2
        - !Ref Subnet3
