AWSTemplateFormatVersion: 2010-09-09
Parameters:	
    location:
        Type: String
        Description: Location for the resources
    pgsqlServerName:
        Type: String
        Description: PostgreSQL server name
    pgsqlAdminLogin:
        Type: String
        Description: PostgreSQL user
    pgsqlAdminPassword:
        Type: String
        Description: PostgreSQL password
Resources:
    s3Bucket:
        Type: 'AWS::S3::Bucket'
        Description: S3 bucket