name: Validate ARM templates

on:
  pull_request:
    branches: [ main, v3-dev ]
    paths:
      - 'templates/**'
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  validate_arm_templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Apply arm-templates label on PR
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['arm-templates']
            })
      - uses: actions/checkout@v3.1.0

      - name: Checkout Azure/arm-ttk
        uses: actions/checkout@v3.1.0
        with: 
          repository: Azure/arm-ttk
          path: arm-ttk
      
      - name: Run arm-ttk
        shell: pwsh
        run: |
          Import-Module ./arm-ttk/arm-ttk/arm-ttk.psd1
          Test-AzTemplate -TemplatePath ./templates
