name: Validate CloudFormation templates

on:
  pull_request:
    branches: [ main, main-vnext ]
    paths:
      - 'templates/aws/**'
  push:
    branches: [ main, main-vnext ]
    paths:
      - 'templates/aws/**'
  workflow_dispatch:

jobs:
  validate_cfn_templates:
    name: Build and Validate CloudFormation Templates
    runs-on: ubuntu-latest
    
    steps:
      - name: Apply cfn-templates label on PR
        uses: actions/github-script@v7
        if: ${{ github.event_name == 'pull_request' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['cfn-templates']
            })
      - uses: actions/checkout@v4.1.4
      
      - name: Check CloudFormation Syntax
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint templates/aws/*.yml