name: Validate CloudFormation templates

on:
  pull_request:
    branches: [ main-vnext ]
    paths:
      - 'templates/aws/**'
  push:
    branches: [ main-vnext ]
    paths:
      - 'templates/aws/**'
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  validate_cfn_templates:
    name: Build and Validate CloudFormation Templates
    runs-on: ubuntu-latest
    
    steps:
      - name: Apply cfn-templates label on PR
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['cfn-templates']
            })
      - uses: actions/checkout@v3.4.0
      
      - name: Check CloudFormation Syntax
        uses: scottbrenner/cfn-lint-action@v2
        with:
          path: templates/aws/